- azure-devops/core/selc-ms-onboarding-interceptor.tf
Add new pipeline for onboarding interceptor microservice
Required new microservice for intercepting onboarding request from kafka queue
---
> add onboarding interceptor pipeline

- azure-devops/pnpg/06_pipeline_selfcare-core-backend.tf
- azure-devops/pnpg/06_pipeline_selfcare-external-api-backend.tf
- azure-devops/pnpg/99_locals.tf
> fix: Update FE conf

- azure-devops/core/99_locals.tf
modified dev_react_app_url_api_party_process value in order to verify new ms-core microservice
link to SELC-2174
---
> SELC-2174 - modified value of dev_react_app_url_api_party_process

- azure-devops/core/99_locals.tf
> added variable for party registry proxy url

- azure-devops/core/99_locals.tf
> modified react_app_url_api_party_process variable in uat env

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
Added a env variable called "react_app_products_asset" for management the products asset
---
> Management through the react_app_products_asset environment variable of the products asset

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
> updated support email

- azure-devops/core/selc-ms-party-registry-proxy.tf
> fix: Update Registry proxy deploy name

- azure-devops/pnpg/06_pipeline_selfcare-fe-login.tf
Edit variable values: react_app_url_file_privacy_disclaimer and react_app_url_file_terms_and_conditions
Changed the values to get specialized links based on the environment
---
> PNPG-200 Edit variable values: react_app_url_file_privacy_disclaimer and react_app_url_file_terms_and_conditions

- azure-devops/core/99_locals.tf
> feat: added env variables for AOO/UO

- azure-devops/core/99_locals.tf
Adding new var for FE to enable alert message
---
> Adding new variable for enable Alert banner on selfcare FE

- azure-devops/pnpg/99_locals.tf
> Update pnpg var react_app_banner_enabled

- azure-devops/core/99_locals.tf
> uat aoo uo enable

- azure-devops/core/selc-ms-external-interceptor.tf
> fix: External interceptor deployment name

- azure-devops/iac/00_secrets_kv_selfcare.tf
- azure-devops/iac/03_iac_selfcare-legacy.tf
- azure-devops/iac/99_variables.tf
Add new iac selfcare legacy pipeline
Selfcare new infra deploy
---
> fix: Add new pipeline for iac-selfcare deploy

- azure-devops/core/hub-spid-login-ms-agid.tf
> adding new pipeline for new hub spid login using new metadata agid

- azure-devops/core/99_locals.tf
> Add Error on selc prod

- azure-devops/ar/.terraform.lock.hcl
- azure-devops/core/.terraform.lock.hcl
- azure-devops/core/10_tlscert-dev-selc-internal-dev-pagopa-it.tf
- azure-devops/iac/.terraform.lock.hcl
Add pipeline for selc.internal.dev.pagopa.it certificate
Update lock files
Old SelfCare AKS cluster needs new certificate for ingress controllers
---
> Add pipeline for selc.internal.dev.pagopa.it certificate

- azure-devops/core/.terraform.lock.hcl
- azure-devops/core/10_tlscert-dev-selc-internal-dev-pagopa-it.tf
- azure-devops/core/10_tlscert-selc-internal-dev-selfcare-pagopa-it.tf
- azure-devops/core/99_main.tf
Update DNS zone for selc-internal-dev-selfcare-pagopa-it and related variables
Match existing public dns zone without creating a new one
---
> Update dns zone name for selc-internal-dev-selfcare-pagopa-it

- azure-devops/core/10_tlscert-selc-internal-uat-selfcare-pagopa-it.tf
Add pipeline for selc.internal.uat.pagopa.it certificate
Old SelfCare AKS cluster needs new certificate for ingress controllers
---
> Add pipeline for selc.internal.uat.pagopa.it certificate

- azure-devops/core/99_locals.tf
> Update 99_locals.tf set prod_react_app_login_spid_enabled to false

- azure-devops/core/10_tlscert-selc-internal-selfcare-pagopa-it.tf
Add pipeline for selc.internal.selfcare.pagopa.it certificate
Old SelfCare AKS cluster needs new certificate for ingress controllers
---
> Add pipeline for selc.internal.selfcare.pagopa.it certificate

- azure-devops/core/99_locals.tf
Turned off PT environment variable
In order to temporarily not allow the participation of technological partners on delegable products, the feature flag has been set to false in the UAT and PROD environments.
---
> [SELC-3430] feat: turned off PT environment variable

- azure-devops/pnpg/99_locals.tf
Used correct support mail for pnpg
In order to send at the correct mail the support request send from pnpg portal
---
> feat: used correct support mail for pnpg

- azure-devops/pnpg/99_locals.tf
Introduced v2 for pnpg environments
Introduced v2 for pnpg environments in order to permanently remove v1
---
> [SELC-4018] feat: Introduced v2 for pnpg environments

- CODEOWNERS
Change codeowners group
Old group doesn't exist anymore
---
> [SELC-2935] Update codeowners

- azure-devops/core/99_locals.tf
updated env variables of onboarding v2
In order to fix bad values
---
> feat: updated env variables of onboarding v2

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
Removing api version from base path. Refactor on Selfcare move some API to other µs.
---
> removing /v1 from base url

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
Update-uat_react_app_url_api_dashboard
In order to remove from uat env variable the version of the dashboard api
---
> [SELC-4341] Update-uat_react_app_url_api_dashboard

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
Removed v1 dashboard fe from core and pnpg for prod env variables
In order to receive environment variable value without versioning also in production for selfcare and pnpg
---
> feat: removed v1 dashboard fe from core and pnpg for prod env variables

- azure-devops/core/99_locals.tf
Add new boolean enviroment variable.
In order to switch from v1 to v2 fo api calls of user suspend, delete , activate
---
> [SELC-4198] Feat: Add env var to enable or disable user v2 api

- azure-devops/pnpg/99_locals.tf
> Add env var to enable user v2 in pnpg user

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/.terraform.lock.hcl
- azure-devops/pnpg/99_locals.tf
* Added /imprese for api-pnpg url that point to dashboard onboarding and proxy-registry
* Remove unused variable
It needed because frontend will call to apim instead aks to retrieve data by backend cause of migration to container apps env.
---
> [SELC-4411] Added /imprese to pnpg url api on dev env

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
Added /imprese for api-pnpg url that point to dashboard onboarding and proxy-registry
Remove unused variable
It needed because frontend will call to apim instead aks to retrieve data by backend cause of migration to container apps env.
---
> [SELC-4411] Added /imprese to pnpg url api on prod env

- azure-devops/core/99_locals.tf
set dev_react_app_enable_user_v2 true
---
> Enable flow to user-ms from frontend DEV

- azure-devops/core/99_locals.tf
> Redirect uat to spid/v1/

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
Enabled v2 user env variable selfcare
Enabled v2 user env variable pnpg
To switch in prod to new user ms
---
> Enabled v2 user env variable for selfcare and pnpg for prod enviroment

- azure-devops/core/99_locals.tf
- azure-devops/pnpg/99_locals.tf
[SELC-4955] feat: Unique basePath for spid login and removed supporting env variable
In order to use unique basePath and clean the code removing the environment variable _react_app_url_api_login_spid_ which is no longer used
---
[SELC-4955]: https://pagopa.atlassian.net/browse/SELC-4955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SELC-4955] feat: Unique basePath for spid login and removed supporting env variable
